name: Update flyteidl-rust nightly

on:
  workflow_dispatch:  # Allow manual triggers
  schedule:
    - cron: "0 * * * *"

permissions: {}
        
jobs:
  release-nightly:
    if: github.repository == 'tensorflow/tensorflow' # Don't do this in forks
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: [linux, musllinux, windows, macos, sdist]
    steps:
      - uses: actions/download-artifact@v4
      - name: Publish to PyPI
        uses: PyO3/maturin-action@v1
        env:
          MATURIN_PYPI_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        with:
          command: upload
          args: --non-interactive --skip-existing --repository-url https://test.pypi.org/simple/ wheels-*/*